{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Car performance\",\"Errors in data\",\"Brand\",\"Model\",\"Car Category\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Errors in data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let\r",
          "Source = #\"Car performance\",\r",
          "  #\"Detected Type Mismatches\" = let\r",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),\r",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),\r",
          "    fieldNames = Record.FieldNames(recordTypeFields),\r",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),\r",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})\r",
          "in\r",
          "    Table.TransformColumns(Source, pairs),\r",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),\r",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Year\", \"Brand\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),\r",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Year\", \"Brand\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"})\r",
          "in\r",
          "    #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "5fb5f8a2-1183-4a86-acda-6d12341b64cc",
        "queryGroup": "Query Errors - 30/01/2025 17:14:35"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 30/01/2025 17:14:35.",
        "folder": "Query Errors - 30/01/2025 17:14:35"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_8fc6a869-9af9-4a6a-aa08-987054c820d6",
        "fromColumn": "ID Brand",
        "fromTable": "Model",
        "toColumn": "ID Brand",
        "toTable": "Brand"
      },
      {
        "name": "f1297951-be98-3650-2279-dd3378f3a373",
        "fromColumn": "ID Model",
        "fromTable": "Car performance",
        "toColumn": "ID Model",
        "toTable": "Model"
      },
      {
        "name": "AutoDetected_ca5ea055-9387-48a1-b8c4-0607ca626ef1",
        "fromColumn": "ID Class",
        "fromTable": "Car performance",
        "toColumn": "ID Class",
        "toTable": "Car Category"
      }
    ],
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "Car performance",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Performance Indicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ea70573-706e-4c36-8729-d5742e408b63",
            "sourceColumn": "Performance Indicator",
            "summarizeBy": "sum"
          },
          {
            "name": "0-60 Sec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0283cdf0-b523-452c-8c21-ead55a7d9e4d",
            "sourceColumn": "0-60 Sec",
            "summarizeBy": "none"
          },
          {
            "name": "0-100 Sec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99b6774c-16e5-44b4-9e69-b317f59f4738",
            "sourceColumn": "0-100 Sec",
            "summarizeBy": "none"
          },
          {
            "name": "Top Speed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e603d28a-3813-4042-8c88-afc68b8be56d",
            "sourceColumn": "Top Speed",
            "summarizeBy": "sum"
          },
          {
            "name": "60-0 Feet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53011375-a27f-4f1b-9a52-0224c8c24bd4",
            "sourceColumn": "60-0 Feet",
            "summarizeBy": "none"
          },
          {
            "name": "100-0 Feet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a496606f-75a8-4cde-abb2-c9a30eb56353",
            "sourceColumn": "100-0 Feet",
            "summarizeBy": "none"
          },
          {
            "name": "60mph g's",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "668770d8-1f40-4c03-8bad-70f8e393049f",
            "sourceColumn": "60mph g's",
            "summarizeBy": "sum"
          },
          {
            "name": "100mph g's",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e47b034a-a3a2-4d71-978c-25c397fba991",
            "sourceColumn": "100mph g's",
            "summarizeBy": "sum"
          },
          {
            "name": "60-100 sec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54047f65-b1f8-4fc5-84a0-31cf8df88544",
            "sourceColumn": "60-100 sec",
            "summarizeBy": "none"
          },
          {
            "name": "ID Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7a48f38-5891-430c-bb2c-ca633c919dc7",
            "sourceColumn": "ID Model",
            "summarizeBy": "none"
          },
          {
            "name": "ID Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "342c74a0-8021-463b-b817-1cdfc38732f0",
            "sourceColumn": "ID Brand",
            "summarizeBy": "none"
          },
          {
            "name": "ID Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c46a6b65-2a14-481c-8cdf-4fa4df251262",
            "sourceColumn": "ID Class",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1db72cf6-a6fb-4ca7-b99c-08e4160cff8a",
        "partitions": [
          {
            "name": "Car performance",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\boudl\\Documents\\Projet Dekra\\PBI_AUTO.github.io\\Projet Dekra\\Test-data.xlsx\"), null, true),",
                "    data_Sheet = Source{[Item=\"data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"Brand\", type text}, {\"MODELS\", type any}, {\"Class\", type text}, {\"Performance Indicator\", Int64.Type}, {\"HP\", Int64.Type}, {\"Torque\", Int64.Type}, {\"Weight\", Int64.Type}, {\"Wt/HP Ratio\", type number}, {\"Engine position\", type text}, {\"Drive\", type text}, {\"Cylinder\", type any}, {\"Country\", type text}, {\"0-60 Sec\", type any}, {\"0-100 Sec\", type any}, {\"Top Speed\", type number}, {\"60-0 Feet\", type any}, {\"100-0 Feet\", type any}, {\"60mph g's\", type number}, {\"100mph g's\", type number}, {\"60-100 sec\", type any}}),",
                "    // Création colonne Index",
                "    #\"Added column Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    // Positionnement de la colonne en 1er",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added column Index\",{\"Index\", \"Year\", \"Brand\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),",
                "    // Renommage de la colonne Index en ID",
                "    #\"Renamed Column Index => ID\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"ID\"}}),",
                "    #\"Added column ID Model\" = Table.AddColumn(#\"Renamed Column Index => ID\", \"ID Model\", each Text.PadStart(Text.From([Year]) & \"_\" & Text.Start([Brand], 1) & \"_\" & Text.Combine(List.Transform(Text.Split([MODELS], \" \"), each Text.Start(_, 3)), \"\") & \"_\" & ",
                "    Text.From([HP]) & \"_\" & ",
                "    Text.From([Torque]) & \"_\" & ",
                "    Text.From([Weight]), ",
                "    15, \"0\"",
                ")),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Added column ID Model\", {\"Brand\"}, Brand, {\"Brand\"}, \"Brand.1\", JoinKind.LeftOuter),",
                "    #\"Expanded Brand.1\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Brand.1\", {\"ID Brand\"}, {\"Brand.1.ID Brand\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Brand.1\",{{\"Brand.1.ID Brand\", \"ID Brand\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"ID Brand\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Brand\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Columns\",{\"ID\", \"ID Model\", \"ID Brand\", \"Year\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Reordered Columns1\",{{\"ID Model\", type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type2\",{{\"Class\", \"ID Class\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"ID\", \"Year\", \"MODELS\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Brand",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6d4f87c-da07-471e-ad48-6eeb19c4b074",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8723fe7-70e4-4534-a193-627506db2e86",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "764ac228-7013-4079-8520-52345f3d763d",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "ID Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31ef459d-6b3f-457a-85ff-1944489ece01",
            "sourceColumn": "ID Brand",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bbcd9fdc-a64b-42bf-9cfd-fd4674492490",
        "partitions": [
          {
            "name": "Brand",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\boudl\\Documents\\Projet Dekra\\PBI_AUTO.github.io\\Projet Dekra\\Test-data.xlsx\"), null, true),",
                "    data_Sheet = Source{[Item=\"data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"Brand\", type text}, {\"MODELS\", type any}, {\"Class\", type text}, {\"Performance Indicator\", Int64.Type}, {\"HP\", Int64.Type}, {\"Torque\", Int64.Type}, {\"Weight\", Int64.Type}, {\"Wt/HP Ratio\", type number}, {\"Engine position\", type text}, {\"Drive\", type text}, {\"Cylinder\", type any}, {\"Country\", type text}, {\"0-60 Sec\", type any}, {\"0-100 Sec\", type any}, {\"Top Speed\", type number}, {\"60-0 Feet\", type any}, {\"100-0 Feet\", type any}, {\"60mph g's\", type number}, {\"100mph g's\", type number}, {\"60-100 sec\", type any}}),",
                "    // Création colonne Index",
                "    #\"Added column Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    // Positionnement de la colonne en 1er",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added column Index\",{\"Index\", \"Year\", \"Brand\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),",
                "    // Renommage de la colonne Index en ID",
                "    #\"Renamed Column Index => ID\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"ID\"}}),",
                "    #\"Added column ID Model\" = Table.AddColumn(#\"Renamed Column Index => ID\", \"ID Model\", each Text.PadStart(Text.From([Year]) & \"_\" & [Brand] & \"_\" & Text.From([MODELS]) & \"_\" & Text.From([HP]) & \"_\" & Text.From([Torque]), 15, \"0\")),",
                "    // Copie de la table de fait, suppression de colonne pour garder les colonnes nécessaire à la table de dimension \"Brand\"",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Added column ID Model\",{\"Brand\", \"Country\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"Brand\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Added Index\", \"ID Brand\", each Text.Upper(Text.Start([Brand], 1)) & Text.PadStart(Text.From([Index]), 3, \"0\"))",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Model",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cb7657a-c3e4-416d-a085-36c52e92cdb9",
            "sourceColumn": "ID Brand",
            "summarizeBy": "none"
          },
          {
            "name": "ID Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9249790-5e10-494c-83a3-fa8cb9a4d634",
            "sourceColumn": "ID Model",
            "summarizeBy": "none"
          },
          {
            "name": "MODELS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "201826fc-19ad-456c-975e-e243fa50d0d9",
            "sourceColumn": "MODELS",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9581b568-dbfa-4753-accf-ef8a8bc93c8b",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "HP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab44a238-d790-4915-90c5-9f3605ddcf10",
            "sourceColumn": "HP",
            "summarizeBy": "sum"
          },
          {
            "name": "Torque",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76e1ffad-c835-4f7e-b972-05f239cc2ae8",
            "sourceColumn": "Torque",
            "summarizeBy": "sum"
          },
          {
            "name": "Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9608d5bd-fb23-4a8d-9e1c-cfbf013c3acd",
            "sourceColumn": "Weight",
            "summarizeBy": "sum"
          },
          {
            "name": "Wt/HP Ratio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "62da96a5-4c38-4a62-8589-e9ee517b2c41",
            "sourceColumn": "Wt/HP Ratio",
            "summarizeBy": "sum"
          },
          {
            "name": "Engine position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd43bba2-ebd2-48c7-9533-1a06892c3274",
            "sourceColumn": "Engine position",
            "summarizeBy": "none"
          },
          {
            "name": "Drive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "878d794c-fa88-4cb9-bf08-97480dc44b14",
            "sourceColumn": "Drive",
            "summarizeBy": "none"
          },
          {
            "name": "Cylinder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7df061fa-616e-4887-87c4-3b029b521e2d",
            "sourceColumn": "Cylinder",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f2e15083-880a-4cde-84a5-8bc7e96fd993",
        "partitions": [
          {
            "name": "Model",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\boudl\\Documents\\Projet Dekra\\PBI_AUTO.github.io\\Projet Dekra\\Test-data.xlsx\"), null, true),",
                "    data_Sheet = Source{[Item=\"data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"Brand\", type text}, {\"MODELS\", type any}, {\"Class\", type text}, {\"Performance Indicator\", Int64.Type}, {\"HP\", Int64.Type}, {\"Torque\", Int64.Type}, {\"Weight\", Int64.Type}, {\"Wt/HP Ratio\", type number}, {\"Engine position\", type text}, {\"Drive\", type text}, {\"Cylinder\", type any}, {\"Country\", type text}, {\"0-60 Sec\", type any}, {\"0-100 Sec\", type any}, {\"Top Speed\", type number}, {\"60-0 Feet\", type any}, {\"100-0 Feet\", type any}, {\"60mph g's\", type number}, {\"100mph g's\", type number}, {\"60-100 sec\", type any}}),",
                "    // Création colonne Index",
                "    #\"Added column Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    // Positionnement de la colonne en 1er",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added column Index\",{\"Index\", \"Year\", \"Brand\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),",
                "    // Renommage de la colonne Index en ID",
                "    #\"Renamed Column Index => ID\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"ID\"}}),",
                "    #\"Added column ID Model\" = Table.AddColumn(#\"Renamed Column Index => ID\", \"ID Model\", each Text.PadStart(Text.From([Year]) & \"_\" & Text.Start([Brand], 1) & \"_\" & Text.Combine(List.Transform(Text.Split([MODELS], \" \"), each Text.Start(_, 3)), \"\") & \"_\" & ",
                "    Text.From([HP]) & \"_\" & ",
                "    Text.From([Torque]) & \"_\" & ",
                "    Text.From([Weight]), ",
                "    15, \"0\"",
                ")),",
                "    // Pour ajouter la colonne ID Brand à la table de fait (avec la correspondance des colonnes Brand)",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Added column ID Model\", {\"Brand\"}, Brand, {\"Brand\"}, \"Brand.1\", JoinKind.LeftOuter),",
                "    #\"Expanded Brand.1\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Brand.1\", {\"ID Brand\"}, {\"Brand.1.ID Brand\"}),",
                "    // Brand.1.ID Brand => ID Brand",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Brand.1\",{{\"Brand.1.ID Brand\", \"ID Brand\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"ID Brand\", type text}}),",
                "    #\"Removed Columns Brand\" = Table.RemoveColumns(#\"Changed Type1\",{\"Brand\"}),",
                "    // Placement des colonnes ID Brand, ID Model en deuxième et troisième position",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Columns Brand\",{\"ID\", \"ID Brand\", \"ID Model\", \"Year\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Reordered Columns1\",{\"ID Brand\", \"ID Model\", \"MODELS\", \"Year\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{{\"ID Model\", type text}, {\"MODELS\", type text}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type2\", {\"ID Model\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Errors\", {\"ID Model\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Duplicates\",null,\"not defined\",Replacer.ReplaceValue,{\"ID Model\"}),",
                "    #\"Replaced Engine P Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"F\",\"Front\",Replacer.ReplaceText,{\"Engine position\"}),",
                "    #\"Replaced Engine P Value2\" = Table.ReplaceValue(#\"Replaced Engine P Value1\",\"R\",\"Rear\",Replacer.ReplaceText,{\"Engine position\"}),",
                "    #\"Replaced Engine P Value3\" = Table.ReplaceValue(#\"Replaced Engine P Value2\",\"M\",\"Middle\",Replacer.ReplaceText,{\"Engine position\"}),",
                "    #\"Replaced Drive Value1\" = Table.ReplaceValue(#\"Replaced Engine P Value3\",\"A\",\"All wheel drive\",Replacer.ReplaceText,{\"Drive\"}),",
                "    #\"Replaced Drive Value2\" = Table.ReplaceValue(#\"Replaced Drive Value1\",\"R\",\"Rear wheel drive\",Replacer.ReplaceText,{\"Drive\"}),",
                "    #\"Replaced Drive Value3\" = Table.ReplaceValue(#\"Replaced Drive Value2\",\"F\",\"Front wheel drive\",Replacer.ReplaceText,{\"Drive\"})",
                "in",
                "    #\"Replaced Drive Value3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Car Category",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be726d02-e736-4cd6-895c-dff476ae0dd3",
            "sourceColumn": "ID Class",
            "summarizeBy": "none"
          },
          {
            "name": "Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa6bbab9-c714-4ae0-ae54-405b4595d0f0",
            "sourceColumn": "Class",
            "summarizeBy": "none"
          },
          {
            "name": "Performance Categoy Car",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "014dcfcb-d415-4504-bc6a-0f44f69fabb2",
            "sourceColumn": "Performance Categoy Car",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ee4bf580-0852-4ccc-bf69-bbdb4804f67b",
        "partitions": [
          {
            "name": "Car Category",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\boudl\\Documents\\Projet Dekra\\PBI_AUTO.github.io\\Projet Dekra\\Test-data.xlsx\"), null, true),",
                "    data_Sheet = Source{[Item=\"data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"Brand\", type text}, {\"MODELS\", type any}, {\"Class\", type text}, {\"Performance Indicator\", Int64.Type}, {\"HP\", Int64.Type}, {\"Torque\", Int64.Type}, {\"Weight\", Int64.Type}, {\"Wt/HP Ratio\", type number}, {\"Engine position\", type text}, {\"Drive\", type text}, {\"Cylinder\", type any}, {\"Country\", type text}, {\"0-60 Sec\", type any}, {\"0-100 Sec\", type any}, {\"Top Speed\", type number}, {\"60-0 Feet\", type any}, {\"100-0 Feet\", type any}, {\"60mph g's\", type number}, {\"100mph g's\", type number}, {\"60-100 sec\", type any}}),",
                "    // Création colonne Index",
                "    #\"Added column Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    // Positionnement de la colonne en 1er",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added column Index\",{\"Index\", \"Year\", \"Brand\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),",
                "    // Renommage de la colonne Index en ID",
                "    #\"Renamed Column Index => ID\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"ID\"}}),",
                "    #\"Added column ID Model\" = Table.AddColumn(#\"Renamed Column Index => ID\", \"ID Model\", each Text.PadStart(Text.From([Year]) & \"_\" & Text.Start([Brand], 1) & \"_\" & Text.Combine(List.Transform(Text.Split([MODELS], \" \"), each Text.Start(_, 3)), \"\") & \"_\" & ",
                "    Text.From([HP]) & \"_\" & ",
                "    Text.From([Torque]) & \"_\" & ",
                "    Text.From([Weight]), ",
                "    15, \"0\"",
                ")),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Added column ID Model\", {\"Brand\"}, Brand, {\"Brand\"}, \"Brand.1\", JoinKind.LeftOuter),",
                "    #\"Expanded Brand.1\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Brand.1\", {\"ID Brand\"}, {\"Brand.1.ID Brand\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Brand.1\",{{\"Brand.1.ID Brand\", \"ID Brand\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"ID Brand\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Brand\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Columns\",{\"ID\", \"ID Model\", \"ID Brand\", \"Year\", \"MODELS\", \"Class\", \"Performance Indicator\", \"HP\", \"Torque\", \"Weight\", \"Wt/HP Ratio\", \"Engine position\", \"Drive\", \"Cylinder\", \"Country\", \"0-60 Sec\", \"0-100 Sec\", \"Top Speed\", \"60-0 Feet\", \"100-0 Feet\", \"60mph g's\", \"100mph g's\", \"60-100 sec\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Reordered Columns1\",{{\"ID Model\", type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type2\",{\"Class\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"Class\", \"ID Class\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"Class\", each if List.Contains({\"E\", \"F\", \"G\", \"H\", \"I\", \"J\", \"K\", \"L\", \"M\", \"N\", \"O\", \"P\", \"Q\",\"R\", \"S\", \"T\", \"U\", \"V\", \"W\", \"X\"}, Text.Upper([ID Class])) then ",
                "    \"Street Cars\"",
                "else if List.Contains({\"R1\", \"R2\", \"R3\", \"R4\"}, Text.Upper([ID Class])) then ",
                "    \"Racing Cars\"",
                "else ",
                "    \"Autres\"),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Class\", type text}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type3\", \"Performance Categoy Car\", each if [Class] = \"Street Cars\" then",
                "    if [ID Class] = \"E\" then \"Low performance car\"",
                "    else if [ID Class] = \"X\" then \"High performance car\"",
                "    else \"Medium performance car\"",
                "else if [Class] = \"Racing Cars\" then",
                "    if [ID Class] = \"R4\" then \"Low performance racing car\"",
                "    else if [ID Class] = \"R1\" then \"High Performance racing car\"",
                "    else \"Medium performance racing car\"",
                "else",
                "    \"Autres\"),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Performance Categoy Car\", type text}})",
                "in",
                "    #\"Changed Type4\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}